# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Static checks

on:
  push:
  pull_request:

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
        - 'python:3.6-slim'
        - 'python:3.7-slim'
        - 'python:3.8-slim'
        - 'python:3.9-slim'

    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2

    - name: Install host dependencies
      run: |
        apt-get -qq update
        apt-get install -qq gcc git
        rm -rf /var/lib/apt/lists/*
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # exit-zero treats all errors as warnings
        # poetry run flake8 . --count --exit-zero --statistics
        poetry run flake8 . --count --exit-zero --statistics
#    - name: Check format with black
#      run: |
 #       poetry run black . --check --diff
